// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzQB--4t2Jk9QpxkKTCnA02sFSYrA6Jf8',
    appId: '1:1034661701520:web:48fe98bc200e7a528ff515',
    messagingSenderId: '1034661701520',
    projectId: 'plant-monitoring-30ac8',
    authDomain: 'plant-monitoring-30ac8.firebaseapp.com',
    storageBucket: 'plant-monitoring-30ac8.firebasestorage.app',
    measurementId: 'G-1YBPPYE03R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVQiraeugD81Z0Za1kabeXP0Jqu5gQmps',
    appId: '1:1034661701520:android:dde5de1a1fa6d4888ff515',
    messagingSenderId: '1034661701520',
    projectId: 'plant-monitoring-30ac8',
    storageBucket: 'plant-monitoring-30ac8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0TkYD_bD1R8FF7WCykmHUh5EtjqGVaNA',
    appId: '1:1034661701520:ios:92d074e38b6f802c8ff515',
    messagingSenderId: '1034661701520',
    projectId: 'plant-monitoring-30ac8',
    storageBucket: 'plant-monitoring-30ac8.firebasestorage.app',
    iosBundleId: 'com.example.plantMonitoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0TkYD_bD1R8FF7WCykmHUh5EtjqGVaNA',
    appId: '1:1034661701520:ios:92d074e38b6f802c8ff515',
    messagingSenderId: '1034661701520',
    projectId: 'plant-monitoring-30ac8',
    storageBucket: 'plant-monitoring-30ac8.firebasestorage.app',
    iosBundleId: 'com.example.plantMonitoring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzQB--4t2Jk9QpxkKTCnA02sFSYrA6Jf8',
    appId: '1:1034661701520:web:7a31903b7ad4cc258ff515',
    messagingSenderId: '1034661701520',
    projectId: 'plant-monitoring-30ac8',
    authDomain: 'plant-monitoring-30ac8.firebaseapp.com',
    storageBucket: 'plant-monitoring-30ac8.firebasestorage.app',
    measurementId: 'G-VXN9CXPXBB',
  );
}
